name: cine_vault
description: "CineVault - A clean architecture Flutter movie app with Bloc."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # State Management
  flutter_bloc: ^8.1.6
  bloc: ^8.1.4
  equatable: ^2.0.5

  # Networking (Dio only - Retrofit later if needed)
  dio: ^5.7.0
  pretty_dio_logger: ^1.4.0

  # Dependency Injection
  get_it: ^8.0.0

  # Local Storage
  shared_preferences: ^2.3.2
  # Hive: NoSQL key-value store with reactive streams (Phase 5 — favorites)
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.4

  # Navigation
  go_router: ^14.6.1

  # UI
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0
  carousel_slider: ^5.0.0
  youtube_player_iframe: ^5.2.0
  url_launcher: ^6.3.1

  # Utils
  intl: ^0.20.2
  connectivity_plus: ^6.1.0
  flutter_dotenv: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  # Code Generation (خفيف دلوقتي)
  build_runner: ^2.4.13
  json_serializable: ^6.8.0

  # Testing
  bloc_test: ^9.1.7
  mocktail: ^1.0.4

flutter:
  uses-material-design: true
  generate: true
  assets:
    - .env
    - assets/images/
    - assets/icons/