name: domain
description: Entities, repository contracts and use cases. Pure Dart.
publish_to: none
version: 0.0.1

environment:
  sdk: ^3.13.0

resolution: workspace

dependencies:
  core_result:
    path: ../core/result
  equatable: ^2.0.5

dev_dependencies:
  mocktail: ^1.0.4
  test: ^1.31.1
